name: supernova
favicon: null
layout_spectrum: 0.8173453228082508
typography_spectrum: 0.2469220352359116
title: Supernova
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffef'
    - '#7c7d75'
    - '#ff0000'
    - '#010010'
    - '#00fbf3'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
