name: supernova
favicon: null
layout_spectrum: 0.8173453228082508
typography_spectrum: 0.2469220352359116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.15547323576174676
  lightness: 0.005088266683742404
  saturation: 0.8917011760640889
  rhythmicContrast: 0.9096991489641368
purpose: []
